name: aide_mobile
version: 0.1.0
description: Aide Flutter mobile app
publish_to: 'none'
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true 